w3c/webrtc-stats

- webrtc-stats.html
For https://github.com/w3c/webrtc-stats/issues/9
> Add RTCRTPStreamStats.mediaType

- webrtc-stats.html
Added one item to the changes since section for 03 feb
> updated spec changes since 03 February.

- .travis.yml
Please also make sure this change gets integrated in the gh-pages branch as well when you will be publishing a new ED.
> Fix .travis.yml YAML syntax

- webrtc-stats.html
@alvestrand @vr000m
(still need to figure out how to keep the ipr bot happy)
> s/remoteId/associateStatsId per discussion in #17

- webrtc-stats.html
See https://lists.w3.org/Archives/Public/public-webrtc/2016May/0073.html for context
> Converted to WebIDL contiguous mode

- webrtc-stats.js
@dontcallmedom could you confirm the data is accurate.
> updating varun's affiliation

- webrtc-stats.html
> added packetsDiscarded and packetsRepaired

- webrtc-stats.html
Fixes the validator warnings posted by @vivienlacourba in #28
> updating HTML5 URIs and EventHandler definition

- webrtc-stats.html
Fixes #12
Fixes #21
Replaces PR #32
> New update of alignment of RTCIceCandidate

- webrtc-stats.html
Fixes the remaining issue in #11 related to RTCCodec. @alvestrand PTAL.
> change RTCCodec to RTCCodecStats,

- webrtc-stats.html
> added dashed enums and crosslinking to stats objects

- webrtc-stats.html
Fix for Issue https://github.com/w3c/webrtc-pc/issues/296
Rebase of PR https://github.com/w3c/webrtc-stats/pull/31
> Adding counters to debug ICE problems

- webrtc-stats.html
This specifies an approach to conformance where other documents specify the conformance they want.
Fixes #23
> Example conformance specification

- webrtc-stats.html
This Cl also includes the result of an "untabify", which makes review
difficult. Apologies.
Fixes #57
> Added QP statistics

- webrtc-stats.html
> Adding "deleted" property to RTCIceCandidateStats.

- webrtc-stats.html
Partial resolution of issue #74
> Rename "RTT" to RoundTripTime

- webrtc-stats.html
The approach sketched is "living document".
Fixes #25
> Added procedures for new stats

- webrtc-stats.html
> Explain "sum and count" design paradigm

- webrtc-stats.html
Fixes #85 by removing the question.
> Remove ssrcids field

- webrtc-stats.html
Resolves issue #105. PTAL and merge @alvestrand
> Changes type of RTCRTPStreamStats.ssrc from string to unsigned long.

- webrtc-stats.html
> Explanation for "remoteSource"

- webrtc-stats.html
> removed cancelled and renamed inprogress with in-progress.

- webrtc-stats.html
- webrtc-stats.js
> aligning codec types with webrtc-pc

- webrtc-stats.html
> fixes issue with TURN URL protocol

- webrtc-stats.html
> moving roundTripTime from outbound to inbound

- webrtc-stats.html
> Adds definitions for RTCDataChannelStats members.

- webrtc-stats.html
Fixes #140 
Spurious changes due to "make tidy".
> Add link from datachannel to transport

- webrtc-stats.html
> Add section on obsoleted stats.

- webrtc-stats.html
> rtt undefined when no RTCP RR

- webrtc-stats.html
> RTCIceCandidatePairStats: packetsSent/Received added.

- webrtc-stats.html
> RTCTransportStats: packetsSent/Received added.

- webrtc-stats.html
> RTCIceCandidatePairStats: Remove writable/readable, add consentExpiredTimestamp

- webrtc-stats.html
> Issue 132/mediastreamtrack priority

- webrtc-stats.html
> definition for 'framesPerSecond'

- webrtc-stats.html
> Adds RTCTransportStats.iceRole

- webrtc-stats.html
Fixes the last open issue proposed in #61.
> stats for number of circuit breaker triggered

- webrtc-stats.html
> Issue 178/packets discarded on send

- webrtc-stats.html
Similar to audioLevel.
Fixes #204.
> RTCMediaStreamTrackStats.voiceActivityFlag added.

- webrtc-stats.html
Fix recently introduced markup issues.
> Fix markup issues

- webrtc-stats.html
> keyFramesSent and keyFramesReceived added

- Makefile
- webrtc-stats.html
Also remove a dead target in the Makefile that had a different
tidy configuration (reduce chance of confusion).
> Run "tidy" on the HTML

- webrtc-stats.html
> signed packetsLost

- webrtc-stats.html
> jitterBufferDelay in seconds

- webrtc-stats.html
> Rebase of Taylor's NetworkType PR

- webrtc-stats.html
> Added Guidelines for getStats() results caching

- security-questionnaire.md
- webrtc-stats.html
based on analysis jointly conducted with @vr000m @alvestrand @aboba
>  Complete security and privacy considerations based on self-review

- webrtc-stats.html
> jitterBufferEmittedCount added (jitterBufferOutput)

- webrtc-stats.html
> RTCQualityLimitationReason and friends

- webrtc-stats.html
> Add packetsDuplicated

- webrtc-stats.html
> fractionLost moved to RTCRemoteInboundRTPStreamStats 

- webrtc-stats.html
> Adds per-DSCP packet counters to RTP streams

- webrtc-stats.html
> Remove references to MSE. Fixes #161

- webrtc-stats.html
> moved packetsDuplicated to the right dictionary

- webrtc-stats.html
> renaming RTCRTPStreamStats to RTCRtpStreamStats

- webrtc-stats.html
> obsolete RTCIceCandidatePairStats priority

- webrtc-stats.html
> Rename "mediaType" to "kind" in RTCRTPStreamStats.

- webrtc-stats.html
Fixes #235 together with https://github.com/w3c/webrtc-pc/pull/1753
Fixes #300
> Define object lifetimes and mention end-of-life emission

- webrtc-stats.html
> Add hugeFramesSent to RTCVideoSenderStats

- webrtc-stats.html
> s/ PeerConnection/ RTCPeerConnection/g

- webrtc-stats.html
> Move RTCIceCandidateStats.isRemote to obsolete section.

- webrtc-stats.html
- webrtc-stats.js
Based on the input from the Director on the proposed transition of this document to CR, this pull request creates a slightly different text for the Editors Draft vs CR draft regarding the functioning of the registry for new stats.
> Clarify role of editors draft for CR transition request

- webrtc-stats.html
Fixes https://github.com/w3c/webrtc-pc/issues/1613
> Added list of forbidden stats for isolated streams.

- webrtc-stats.html
fix for https://github.com/w3c/webrtc-stats/issues/362
> typo fix in receiver section

- webrtc-stats.html
> Add TLS version and TLS group to RTCTransportStats

- webrtc-stats.html
> Add fecPacketsDiscarded

- webrtc-stats.html
> Clarify concealedSamples

- webrtc-stats.html
> Add silentConcealedSamples

- webrtc-stats.html
> Add note about simulcast having multiple SSRCs

- webrtc-stats.html
> Fix warnings from respec on broken automatic links

- webrtc-stats.html
> totalEncodedBytesTarget added

- webrtc-stats-testing.md
> initial commit for webrtc-stats-testing

- webrtc-stats.html
> totalPacketSendDelay added

- webrtc-stats.html
> Add RTCInboundRtpStreamStats.totalDecodeTime

- webrtc-stats.html
Fixes for https://github.com/w3c/webrtc-stats/issues/455
> fixing most of the respec issues.

- webrtc-stats.html
Related to https://github.com/w3c/webrtc-stats/issues/356
> Remove RTCIceCandidateStats deleted property

- webrtc-stats.html
Fixes #476.
Please take a look @vr000m and @alvestrand
> RTCOutboundRtpStreamStats.qualityLimitationResolutionChanges added.

- webrtc-stats.html
> adding frames discarded on send

- webrtc-stats.html
> packet vs report block

- webrtc-stats.html
> Packets and Bytes Discard on send for ICE candidate pair

- webrtc-stats.html
> ice-server instead of stunserverconnection

- webrtc-stats.html
> adding totalRoundTripTime, reportsReceived, reportsSent

- webrtc-stats.html
> Adds RTCOutboundRtpStreamStats.rid

- webrtc-stats.html
> SILK and CELT mode sample counters

- webrtc-stats.html
> making sure that unsigned long long is used for packet counters

- webrtc-stats.html
> Add obsolete receiver attachment stats.

- webrtc-stats.html
> Add totalInterFrameDelaySquared to RTCInboundRtpStreamStats

- webrtc-stats.html
Fixes #480.
Fixes #472.
Also need to create a webrtc-pc PR.
> Remove all references to onstatsended

- webrtc-stats.html
Fixes #478.
Fixes #396 (by making it obsolete).
> RTCRtpTransceiverStats added.

- webrtc-stats.html
> RTCSctpTransportStats with smoothedRoundTripTime added.

- webrtc-stats.html
> Add frameBitDepth to RTCInboundRtpStreamStats and RTCOutboundRtpStreamStats

- webrtc-stats.html
> Make RTCMediaStreamStats obsolete

- webrtc-stats.html
> Move 'track' stats to the obsolete section

- webrtc-stats.html
Fixes #440.
(Makes #504 obsolete)
> Clarify qualityLimitationReason priority order

- webrtc-stats.html
Avoid repetition throughout the document
> Factor out definition of audio sample

- webrtc-stats.html
added congestionWindow, receiverWindow, mtu,  unackdata
fixes https://github.com/w3c/webrtc-stats/issues/548
fixes https://github.com/w3c/webrtc-stats/issues/377
> RTCSctpTransportStats additional stats

- webrtc-stats.html
Also a couple of drive-by language fixes.
Fixes #556
> Noted that byte counts don't include connectivity checks.

- webrtc-stats.html
> Move Priority to the obsolete section

- webrtc-stats.html
> Update targetBitrate definition

- webrtc-stats.html
> Add iceState to RTCTransportStats

- webrtc-stats.html
> remoteSource obsolete, relayedSource added

- webrtc-stats.html
> Add ICE ufrag to RTCTransportStats

- webrtc-stats.html
> Make trackIds obsolete

- webrtc-stats.html
> clarifies JB metric measurement

- webrtc-stats.js
> Add Henrik B to the list of editors

- webrtc-stats.html
> playout delay

- webrtc-stats.html
> Describe what we mean by ssrc for remote stats.

- .pr-preview.json
- CONTRIBUTING.md
- LICENSE.md
- webrtc-stats.html
> Fix repo administrativia

- webrtc-stats.html
***
<a href="https://pr-preview.s3.amazonaws.com/balazskreith/webrtc-stats/pull/604.html" title="Last updated on Jun 11, 2021, 4:41 AM UTC (5cf86fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/604/dce502b...balazskreith:5cf86fb.html" title="Last updated on Jun 11, 2021, 4:41 AM UTC (5cf86fb)">Diff</a>
> RTCMediaHandlerStats.remoteSource description

- webrtc-stats.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/pull/608.html" title="Last updated on Jul 5, 2021, 12:33 PM UTC (0038ac7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/608/b6cd94d...0038ac7.html" title="Last updated on Jul 5, 2021, 12:33 PM UTC (0038ac7)">Diff</a>
> Marking references to RFC2032 & 4587 as informative

- webrtc-stats.html
> Fix recently introduced typos.

- webrtc-stats.html
close #691
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/pull/693.html" title="Last updated on Sep 26, 2022, 4:56 AM UTC (a10f6df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/693/84f007f...a10f6df.html" title="Last updated on Sep 26, 2022, 4:56 AM UTC (a10f6df)">Diff</a>
> Add media-playout to summary table

- webrtc-stats.html
Fixes #696
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/697.html" title="Last updated on Sep 27, 2022, 1:37 PM UTC (0c4c318)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/697/93df8b6...henbos:0c4c318.html" title="Last updated on Sep 27, 2022, 1:37 PM UTC (0c4c318)">Diff</a>
> r/"Privacy considerations"/"Procedures for mitigating privacy concerns"

- webrtc-stats.html
fixes #658
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/663.html" title="Last updated on Sep 27, 2022, 2:27 PM UTC (4236810)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/663/6377f0c...fippo:4236810.html" title="Last updated on Sep 27, 2022, 2:27 PM UTC (4236810)">Diff</a>
> clarify nackCount, firCount, pliCount

- webrtc-stats.html
Fixes #698
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/703.html" title="Last updated on Oct 3, 2022, 3:35 PM UTC (195ee0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/703/cd1ff2f...henbos:195ee0b.html" title="Last updated on Oct 3, 2022, 3:35 PM UTC (195ee0b)">Diff</a>
> Allow HW exposure in fullscreen mode

- webrtc-stats.js
> Change in affiliation

- webrtc-stats.html
Fixes #727
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/728.html" title="Last updated on Jan 25, 2023, 10:31 AM UTC (05f71c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/728/d65d1b0...henbos:05f71c8.html" title="Last updated on Jan 25, 2023, 10:31 AM UTC (05f71c8)">Diff</a>
> Add "kind" to RTCAudioPlayoutStats

- webrtc-stats.html
fixes #737 (there is more)
Please review individual commits, pay particular attention to the one about DLSR things
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/739.html" title="Last updated on Mar 7, 2023, 2:13 PM UTC (23768a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/739/e148089...fippo:23768a4.html" title="Last updated on Mar 7, 2023, 2:13 PM UTC (23768a4)">Diff</a>
> Clarify "exists" and "only defined for"

- webrtc-stats.html
fixes #789
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/795.html" title="Last updated on Feb 6, 2025, 5:59 PM UTC (f747146)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/795/02094bc...fippo:f747146.html" title="Last updated on Feb 6, 2025, 5:59 PM UTC (f747146)">Diff</a>
> Do not expose unknown usernameFragment to stats

- .github/workflows/auto-publish.yml
see https://github.com/w3c/webrtc-pc/pull/3035
> github-actions: use ubuntu-latest
