w3c/webrtc-stats

webrtc-stats.html

related to webrtc-ACTION-117: Move getstats and associated idl to stats doc

Keeping getStats in core spec and changing enums to strings

---

W3CTRMANIFEST
webrtc-stats.js

W3C is setting up a new [automated publication workflow](http://www.w3.org/2014/08/pubworkflow.html) for Working Drafts; I would like to use this document as one of the first few to be published that way, and this pull request brings some of the necessary metadata to that end.
For now, this doesn't mean that editor draft releases will be published automatically as TR Working Drafts; just that the next WD publication will be using the new workflow.

setting up for automatic publication on TR

---

webrtc-stats.html

Chrome complains about mixed content when visiting this page over HTTPS, should always use protocol agnostic links.

Remove protocol from src link

---

.travis.yml
README.md
W3CTRMANIFEST
webrtc-stats.html
webrtc-stats.js

This also include use of HTTPS for some URIs and a validation fix.
PR to merge after the ["Call for consensus to implement automatic publishing"](https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html) March 18th 2016 deadline.

Automatic publications with Echidna+Travis and minor respec changes

---

webrtc-stats.html

These stats have been requested.

Ended and detached stats for a track.

---

webrtc-stats.html

Using the definition of bitrate from RFC3890. Fixes #13.

adding bitrate definitions to the spec

---

webrtc-stats.html

possible way forward on issue #37.

setting units to seconds

---

webrtc-stats.html

This PR balances a number of unbalanced &lt;section> directives, and moves
one example section.

Clean up table of content

---

webrtc-stats.html
webrtc-stats.js

Moved metrics from: https://tools.ietf.org/html/draft-ietf-xrblock-rtcweb-rtcp-xr-metrics
Fixes #35.

adding XRBLOCK metrics

---

webrtc-stats.html

Fixes #5
Partially addresses #55

Added text about which specification is authoritative.

---

webrtc-stats.html

Went through the document and removed all occurences of "media stream",
and did some other cleanups.
Fixes #58

Introduced the term "RTP stream", with definition.

---

webrtc-stats.html

Assuming "codec" is what we want for RTCCodecStats.
Also adding a missing description for "codecId".

Adding missing "codec" RTCStatsType.

---

webrtc-stats.html

Adds design guidance on adding stats, on stats values when not relevant,
and on stats lifetimes.
Closes #20
Note: #20 says that we need to note that zero is a valid value for jitter,
so can't be used as an initial value for "not set yet". This isn't added.

Design considerations section

---

webrtc-stats.html

The new summary should make it clear that there is a 1:1 mapping between
an RTCTransportStats and an RTCDtlsTransport/RTCIceTransport pair.
Meaning, when RTCP muxing is _not_ used, you get separate
RTCTransportStats for RTP and RTCP. Also adding links to the appropriate
terms, and to WebRTC (to describe RTCP muxing and bundling in more
detail).

Fixing the summary of RTCTransportStats (issue #72).

---

webrtc-stats.html

Used to differentiate local and remote ICE candidates, which is needed
if the candidate is not paired.
Fixes issue #91.

Adding isRemote to RTCIceCandidateStats.

---

webrtc-stats.html

Needed to associate a candidate with a transport in case the candidate
is not paired.
Fixes issue #92.

Add transportId to RTCIceCandidateStats.

---

webrtc-stats.html

adds a description of issuerCertificateId and tweaks the other descriptions.
Fixes #100.

certificate stats: describe issuerCertificateId

---

webrtc-stats.html

A stats object is created at the same time as the underlying object; NOT
when getStats is called. That means that if an underlying object is
created and destroyed in-between an application calling getStats, it
should still appear in the stats.

Adding minor clarification regarding stats object lifetime.

---

webrtc-stats.html

This also untangles some definitions, and adds a link to the certificate
data type from the identifier spec.
Closes #80

Fix RTCStatsType for "stream"

---

webrtc-stats.html

Also noted that the RTCRTPStreamStats MediaType MUST match the
track it's attached to.
Closes #84

Added "kind" to RTCMediaStreamTrackStats.

---

webrtc-stats.html

This definition should match the one in mediacapture-main for "volume",
and also shows how to relate it to RFC 6465 levels.
Fixes #81

Define audio level rigidly

---

webrtc-stats.html

"active" was not well defined. "state" is more specific, and
is well defined.
Closes #67

Replace RTCTransportStats.active with .dtlsState

---

webrtc-stats.html

This splits the datachannel open events into outgoing and incoming,
and the close events into "I close" and "others close".
Closes #79

Added more datachannel counters, with definitions.

---

webrtc-stats.html

This should make it clear that this document only defines objects.
Closes #115

Remove references saying "defines an API"

---

webrtc-stats.html

The stats for the frameWidth and frameHeight should be for the last
decoded frame. This is for consistency with the MediaElement width/height
which does not change when there are temporarily no frames received.

frameWidth/frameHeight: use last decoded value

---

webrtc-stats.html

This defines a "stats object" as the invisible object that keeps
track of stats, and coins the term "stats value set" for the object
that is returned from the API.
Closes #137
Closes #136

Define terminology for "stats object" et al.

---

webrtc-stats.html

This makes it clear that one track attachment exists for each time
the track is attached.
Closes #130

Make a RTCMediaStreamTrackStats object per track attachment

---

webrtc-stats.html

It seems to be impossible for a receiver of such a request to tell
why it was sent, so we should not try to differentiate on either
incoming requests, outgoing responses or incoming responses.
Fixes #96

Remove separation of received consent and connectivity requests.

---

webrtc-stats.html

Since `timestamp` always refers to the locally measured timestamp,
as decided by the working group, this is where the remote timestamp can
be found.
See: https://github.com/w3c/webrtc-pc/issues/729

Adding remoteTimestamp to RTCRtpStreamStats.

---

webrtc-stats.html

corresponds to issues reported in #86, #97, and #112. related to outgoing and incoming bitrate estimates on a candidate pair.
Tries to undo the git rebase hassle in #170.

Bandwidth estimations again (Issue 97 redux)

---

webrtc-stats.html

Note that "make tidy" inserts an extra space for reasons unknown.
It is too tedious to remove it by hand, so it's left in.

Change log, and make tidy

---

webrtc-stats.html

The getStats example is outdated compared to [the one in the webrtc spec](http://w3c.github.io/webrtc-pc/#getstats-example). Fix this + use new `sender.getStats()`.

Update example to match webrtc spec's + senders.getStats.

---

webrtc-stats.html

RTCMediaStreamTrackStats: framesCaptured added.

---

webrtc-stats.html

Fix for https://github.com/w3c/webrtc-stats/issues/189.
I found it affirming that this PR revealed to me that the stats examples in both specs have always been broken (they never tested for `!isRemote`)!
@alvestrand PTAL - I'll try to add a slide for tomorrow.

Refactor out isRemote.

---

webrtc-stats.html

Fixes #109.
The codec type indicates if it's a media format the implementation is
prepared to encode or decode, and the transportId identifies what RTP
session it's being used for.
An implementation of getStats may want to return RTCCodecStats objects
for codecs not being actively used, in which case these fields are
necessary in order for those objects to provide meaningful information.

Adding "codec type" and transportId to RTCCodecStats.

---

webrtc-stats.html

Reference RTCRtpSynchronizationSource.audioLevel instead of RTCRtpContributingSource.audioLevel.
Fixes #205.

RTCMediaStreamTrackStats.audioLevel: Reference RTCRtpSynchronizationSource

---

webrtc-stats.html

Add paragraph about timestamp and reference DOMHighResTimeStamp

---

webrtc-stats.html

Fixes #183.
This object represents a source that's contributing to a mixed RTP
stream (identified by rtpStreamStatsId). It offers the same information
as RTCRtpContributingSource in the WebRTC 1.0 API, with the addition of
a "packetsContributedTo" counter.

Adding RTCRTPContributingSourceStats stats report object.

---

webrtc-stats.html

Fixes the last open issue proposed in #151.

jitter buffer delay added to media stream tracks

---

webrtc-stats.html

RTCIceCandidatePairStats.last[Request/Response]Timestamp added

---

webrtc-stats.html

Fixes #220.
It's slightly different than most of the stats of this sort, since the
application needs to compute "sqrt(a/b)", not just "a/b". But the
concept is the same.

Adding audio level stat that can be used to compute averages.

---

webrtc-stats.html

Fix for https://github.com/w3c/webrtc-stats/issues/232.

s/Packet Loss Indication/Picture Loss Indication/

---

webrtc-stats.html

Was it accidental or intentional to name the field `datachannelid` instead of `datachannelId`?
If it was not intentional, this PR rename  the field to follow the same camelCase convention as other Id fields.

Typo fix datachannelid to datachannelId

---

webrtc-stats.html

Fixes #249.
This could be a useful statistic for diagnosing why calls are failing,
in case an SRTP-related bug is introduced somewhere.

Add "packetsFailedDecryption", to count SRTP decryption failures.

---

webrtc-stats.html

Add a paragraph about "identifier" when "id" is occupied

---

webrtc-stats.html

Fixes #248
Note: https://github.com/tobie/specref/pull/428 adds
[[IANA-DTLS-SRTP]] and [[IANA-TLS-CIPHERS]] to specref; PR should be
updated with these if it lands before this one is ready.

Adding dtlsCipher and srtpCipher

---

webrtc-stats.html

#270 broke travis build. Despite using `&lt;` and `&gt;` it got confused. Attempted temporary fix to replace them with parenthesis but that also failed the travis build. Using underscores.
Broken build: https://travis-ci.org/w3c/webrtc-stats/builds/313432008
Temporary fix:
record_RTCQualityLimitationReason__double_
Should be:
record<RTCQualityLimitationReason, double>
I'll file a bug. Maybe ReSpec needs to be fixed.

Use underlines instead of record<a,b> for qualityLimitationDurations

---

webrtc-stats.html

Fixes #131 
Note: Attribute could have been named "deleted", but that name is already in use in the "candidate" sub-directory with a different meaning.

Added 'objectDeleted' attribute

---

webrtc-stats.html

Relates to #281 but does not fix the issue unless we decide that DOMString is the way to go.

qualityLimitationDurations record with DOMString key

---

webrtc-stats.html

Fix for https://github.com/w3c/webrtc-stats/issues/231 (includes/on-top-of patch from https://github.com/w3c/webrtc-stats/pull/272).

Add "sender" and "receiver" stats.

---

webrtc-stats.html

Added a hierarchical explainer for what the different
dictionaries in the hierarchy do. Should be reviewed after formatting!

Introduction to RTP stream statistics

---

webrtc-stats.html

Fix for https://github.com/w3c/webrtc-pc/issues/1734 (along with https://github.com/w3c/webrtc-pc/pull/1736).

Remove reference to RTCRtpSynchronizationSource.audioLevel.

---

webrtc-stats.html

Fixes #239 (by answering "yes").

Additional description of audioLevel

---

webrtc-stats.html

An attempt fix the issue with timestamp live (local) and reported (remote) stats. Fixes #313

fix for timestamp for remote and local objects

---

webrtc-stats.html

Fixes #295 
would appreciate review from @bzbarsky

Define timestamps as performance.timeOrigin + performance.now()

---

webrtc-stats.html

Fixes #293.
`receiverId` added to `RTCInboundRTPStreamStats`
and
`senderId` added to `RTCOutboundRTPStreamStats`.
For reference, this is the RTCRTPStreamStats hierarchy:
```
RTCRTPStreamStats
RTCReceivedRTPStreamStats
RTCInboundRTPStreamStats
RTCRemoteInboundRTPStreamStats
RTCSentRTPStreamStats
RTCOutboundRTPStreamStats
RTCRemoteOutboundRTPStreamStats
```

senderId and receiverId added to RTCRTPStreamStats

---

webrtc-stats.html

Fixes #298.
Top-level rename (old => new):
```
RTCMediaStreamTrackStats => RTCMediaHandlerStats
```
Audio names:
```
RTCAudioStreamTrackStats => RTCAudioHandlerStats
RTCAudioSenderStats (not renamed)
RTCAudioReceiverStats (not renamed)
RTCLocalAudioStreamTrackStats => RTCSenderAudioTrackAttachmentStats
```
Video names:
```
RTCVideoStreamTrackStats => RTCVideoHandlerStats
RTCVideoSenderStats (not renamed)
RTCVideoReceiverStats (not renamed)
RTCLocalVideoStreamTrackStats => RTCSenderVideoTrackAttachmentStats
```
This forms the following hierarchy:
```
DICTIONARY NAME                          | INSTANCE FOUND BY
-----------------------------------------+--------------------------------------
RTCMediaHandlerStats                     | N/A
RTCAudioHandlerStats                   | N/A …
```

Rename sender/receiver/track dictionaries

---

.travis.yml

- Use Node LTS version
- Cache NPM packages
- Now using Chrome headless instead of Xvfb for browser testing
- GCC, cmake, python 2.x and 3.x are installed by default on Travis

Update webrtc-respec-ci integration following respec current practices

---

webrtc-stats.html

Fixes #341.
Updated the description: Only applicable for 'track' stats.

Re-added remoteSource to RTCMediaHandlerStats

---

webrtc-stats.html

Fixes #350
- RTCIceCandidateStats.transportId is the ID of an RTCTransportStats,
not another RTCIceCandidateStats
- RTCIceCandidatePairStats.localCandidateId and remoteCandidateId are
IDs of RTCIceCandidateStats, not RTCIceCandidateAttributes (there's
no such thing).

Fixing some descriptions of ID references between stats objects.

---

webrtc-stats.html

simplifies the language of the relayProtocol definition and avoids
confusion with TURN urls

relayprotocol: simplifiy language

---

webrtc-stats.html

Fix for https://github.com/w3c/webrtc-pc/issues/1913.

Rename RTCIceCandidateStats.ip to address.

---

webrtc-stats.html

also restrict it to local candidates

fix rtcicecandidate url description

---

webrtc-stats.html

Introduced in https://github.com/w3c/webrtc-stats/pull/327, right after
https://github.com/w3c/webrtc-stats/pull/333 renamed the dictionary.

Fix capitalization mismatch in RTCRTPStreamStats

---

webrtc-stats.html

Adds RTCStunServerConnectionStats as discussed as discussed in issue #339 .
I have added networkType, as I think it might be useful if the server is not responding (can be an access network issue).
Some questions:
1. do we want to have networkType here? if yes, should it remain as a subsection of ICE candidate stats?
2. with url, local address and port, I think we can uniquely link these stats to relevant candidates if wanted, or am I missing something? :)
3. is having url only to describe the server enough? with DNS load balancers it would be possible to have several servers behind a url

add stunserverconnectionstats

---

webrtc-stats.html

Also emphasize that conformance text is "example only".
Fixes #388

Add RTCInboundStreamStats.fractionLost to obsolete stats

---

webrtc-stats.html

Fix for https://github.com/w3c/webrtc-stats/issues/312.

Move {fir|pli|nack|sli}Count and qpSum out of baseclass to {in|out}bound (Editorial)

---

webrtc-stats.html

Introduced in https://github.com/w3c/webrtc-stats/pull/389.
Original dictionary definition:
https://w3c.github.io/webrtc-stats/#inboundrtpstats-dict*

Fix partial dictionary RTCInboundRtpStreamStats typo

---

webrtc-stats.html

Add insertedSamplesForDeceleration and removedSamplesForAcceleration

---

webrtc-stats.html

Fixes #400. Fixes #422.
Related work not done in this PR: [Move all stream stats from the "sender"/"receiver" stats](https://github.com/w3c/webrtc-stats/issues/402).
The parent dictionary is called RTCMediaSourceStats with type "media-source" (rather than RTCMediaStreamTrackStats or type "track" because those names are already in use by current/legacy dictionaries) and it has two subdictionaries: RTCAudioSourceStats and RTCVideoSourceStats.

Add RTCMediaSourceStats dictionaries for pre-encoding metrics

---

webrtc-stats.html

Moving keyFramesSent on sender to keyFramesEncoded on outbound-rtp, as per offline discussion with @henbos.

Replace RTCVideo{Sender,Receiver}Stats::keyFrames{Sent,Received} with RTC{Out,In}boundRtpStreamStats::keyFrames{En,De}coded

---

webrtc-stats.html

Fixes #449.
Before this PR:
- audioLevel, totalAudioEnergy and totalSamplesDuration were present in both "sender" and "receiver" dictionaries.
After this PR:
- audioLevel, totalAudioEnergy and totalSamplesDuration are present in "receiver" and "media-source" instead.
The difference is even if we are not sending samples (we are not connected), the "media-source" can provide energy levels based on samples produced by the media source (the MediaStreamTrack).

Move audio levels to "media-source" and "receiver"

---

webrtc-stats.html

deleted is a term that can have several meaning.
This PR adds a link to stats-deleted where appropriate to ease readability of the spec.

Add links to deleted definition where applicable

---

webrtc-stats.html

objectDeleted is not really defined.
This wording is probably redundant with https://w3c.github.io/webrtc-stats/#dom-rtcstatstype-track, which refers to RTCRtpSender track change.

Remove references to the notion of objectDeleted in tracks

---

webrtc-stats.html

Remove 'Contains' in a few places to improve consistency of each statstype description

---

webrtc-stats.html

Partial fix for #402.
The following stats have been moved:
**RTCVideoHandlerStats**
- frameWidth, frameHeight: Moved to RTCOutboundRtpStreamStats and RTCInboundRtpStreamStats represending encoded and decoded frames.
- framesPerSecond: For source stats, we already have RTCVideoSourceStats.framesPerSecond (i.e. camera FPS). In this PR framesPerSecond was added to RTCOutboundRtpStreamStats, but representing the encoding frame rate, which previously did not exist. For the receiving case, this was moved to RTCInboundRtpStreamStats representing the decoding frame rate.
**RTCVideoSenderStats**
- framesCaptured: Obsolete. We already have RTCMediaSourceStats.frames.
- framesSent, hugeFramesSent: Moved to RTCOutboundRtpStreamStats.
**RTCAudioHandlerStats**
- voiceActivityFlag: This was moved to …

Move "sender" stats to "outbound-rtp", "inbound-rtp" and "media-source"

---

webrtc-stats.html

This is a follow-up to #463 that fixes the remaining issues of #402 .
This PR moves all RTCAudioReceiverStats and RTCVideoReceiverStats to RTCInboundRtpStreamStats. This means the following metrics:
**RTCAudioReceiverStats**
- estimatedPlayoutTimestamp
- jitterBufferDelay
- jitterBufferEmittedCount
- totalSamplesReceived
- concealedSamples
- silentConcealedSamples
- concealmentEvents
- insertedSamplesForDeceleration
- removedSamplesForAcceleration
- audioLevel
- totalAudioEnergy
- totalSamplesDuration
**RTCVideoReceiverStats**
- estimatedPlayoutTimestamp
- jitterBufferDelay
- jitterBufferEmittedCount
- framesReceived
- framesDecoded
- framesDropped
- partialFramesLost
- fullFramesLost;

Move "receiver" stats to "inbound-rtp"

---

webrtc-stats.html

Fixes some Travis errors introduced by #466 and #463.
See #468 
Removed duplicate framesDecoded and make partial dictionaries not repeat the inheritance

Fix respec issues

---

webrtc-stats.html

Fixes #445 
Which encoder or decoder is used is a property of the RTP stream, not a property of the codec. For example, it is possible that one stream uses an H264 hardware decoder but another stream, having experienced decoding errors and fallen back to software, uses an H264 software decoder. Both RTCInboundRtpStream objects would reference the same RTCCodecStats; the codec stats are tightly coupled with the list if supported/negotiated codecs in the SDP.
This PR allows Chrome to ship this in M78: https://webrtc-review.googlesource.com/c/src/+/149168

Move RTCCodecStats.implementation to RTC[In/Out]boundRtpStreamStats.[decoder/encoder]Implementation

---

webrtc-stats.html

Fixes #474
This can happen due to ICE restarts or it can happen spontaneously if continuous renomination (extension spec) is supported. A higher count in selected candidate pair changes (ICE reroutes) may correlate with worse quality.

Add RTCTransportStats.selectedCandidatePairChanges

---

webrtc-stats.html

If these are reported in XR blocks, these metrics should be in RTCReceivedRtpStreamStats and not in RTCInboundRtpStreamStats

Clarify Cumulative metric for XR blocks and not interval and move to right dictionary

---

webrtc-stats.html

Fixes #448.
Alternatively we could avoid copy-pasting the same paragraph all over the places by defining this once in the beginning of the document, perhaps that is preferred, what do you think?

Added note about channels for all sample based metrics

---

webrtc-stats.css

Redundants with ReSpec-provided text

Remove CSS WebIDL prefix

---

webrtc-stats.html

Clarify how RTX works and adds the rtxSsrc stat

---

webrtc-stats.html

Add counters for bytes sent by ICE pings (#534)

---

webrtc-stats.html
webrtc-stats.js

[WebIDL no longer defines a dictionary member as present](https://github.com/heycam/webidl/commit/8d4e7ca67bcb4de476aab0411531dc97f6d17e0d) but instead makes use of [map existence](https://infra.spec.whatwg.org/#map-exists) as terminology. The spec is updated to make a similar usage.

Adapt references to dictionary member existence

---

webrtc-stats.html

Add "required" specifiers within dictionaries

---

webrtc-stats.html

for issue #512 
clarifying the RTCIceServerStats protocol by renaming to relayProtocol and using similar text and naming than in RTCIceCandidateStats

RTCIceServerStats relayProtocol

---

webrtc-stats.html

fixes a missing word and removes another word which is in the wrong place

clarify roundtriptimemeasurements

---

webrtc-stats.css
webrtc-stats.html
webrtc-stats.js

close #577
The postProcess function  looks at the stats type listed in the table under the appendix with id summary, and for each dictionary listed for the said type looks up the IDL fragment, parses it, identifies inherited dictionaries, and lists all the members for each of those (not mentioning empty dictionaries).
Only non-obsolete stats types are included in the said appendix.

Generate appendix with flatten hierarchy of stats

---

webrtc-stats.html

Only the imported IDL fragment is meant to be information-only

Make concept definitions normative

---

webrtc-stats.html
webrtc-stats.js

Fixes https://github.com/w3c/webrtc-stats/issues/592
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webrtc-stats/pull/591.html" title="Last updated on Jan 20, 2021, 12:39 PM UTC (194a2f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/591/9c46e59...jan-ivar:194a2f7.html" title="Last updated on Jan 20, 2021, 12:39 PM UTC (194a2f7)">Diff</a>

Correct packetsReceived sender-side algorithm to rely on RR.

---

webrtc-stats.html

Should be `unsigned long` rather than `frames`
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 5, 2021, 2:55 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Ftjwudi%2Fwebrtc-stats%2F3fde48fbf509b8770edb52052cb87fd75518ce4a%2Fwebrtc-stats.html%3FisPreview%3Dtrue)
```
📡 HTTP Error 429: https://rawcdn.githack.com/tjwudi/webrtc-stats/3fde48fbf509b8770edb52052cb87fd75518ce4a/webrtc-stats.html
``` …

Wrong type for video_source_stats.frames

---

webrtc-stats.html
webrtc-stats.js

per https://mailarchive.ietf.org/arch/msg/tools-discuss/oYrAxb3KayPzZ4SNB1DVZTDPPNo/
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/pull/599.html" title="Last updated on Mar 16, 2021, 8:56 AM UTC (d01500f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/599/9405d5b...d01500f.html" title="Last updated on Mar 16, 2021, 8:56 AM UTC (d01500f)">Diff</a>

Update links to IETF to use datatracker rather than tools.ietf.org

---

webrtc-stats.html

***
<a href="https://pr-preview.s3.amazonaws.com/minyuel/webrtc-stats/pull/603.html" title="Last updated on Apr 27, 2021, 8:15 PM UTC (b43c9cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/603/0ba4e81...minyuel:b43c9cd.html" title="Last updated on Apr 27, 2021, 8:15 PM UTC (b43c9cd)">Diff</a>

Add RTT stats to RemoteOutboundRtpStreamStats

---

webrtc-stats.html

Needed for stats summary table. Close #606
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/pull/607.html" title="Last updated on Jun 23, 2021, 8:54 AM UTC (a39753b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/607/7bc292b...a39753b.html" title="Last updated on Jun 23, 2021, 8:54 AM UTC (a39753b)">Diff</a>

Fix import of WebIDL2 library

---

webrtc-stats.html

Fixes https://github.com/w3c/webrtc-stats/issues/615.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webrtc-stats/pull/618.html" title="Last updated on Jan 21, 2022, 6:35 PM UTC (67dbc3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/618/0a0a1d2...jan-ivar:67dbc3d.html" title="Last updated on Jan 21, 2022, 6:35 PM UTC (67dbc3d)">Diff</a>

Match channels stat language with that of channels parameter.

---

webrtc-stats.html
webrtc-stats.js

should unbreak CI
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/pull/630.html" title="Last updated on Apr 21, 2022, 7:15 PM UTC (f4b969e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/630/6c49aeb...f4b969e.html" title="Last updated on Apr 21, 2022, 7:15 PM UTC (f4b969e)">Diff</a>

Fix definitions to make respec happy

---

webrtc-stats.html

describing the DTLS role (client/server) the connection has.
Unknown before the DTLS handshake starts.
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/629.html" title="Last updated on Apr 22, 2022, 7:35 AM UTC (7c0a175)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/629/69bcc63...fippo:7c0a175.html" title="Last updated on Apr 22, 2022, 7:35 AM UTC (7c0a175)">Diff</a>

transport: add dtlsRole

---

webrtc-stats.html

see also https://github.com/w3c/media-source/issues/307#issuecomment-1110865467
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 28, 2022, 12:55 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebrtc-stats%2F4f36fd9714101736d6532a5beddac7fad8ae5084%2Fwebrtc-stats.html%3FisPreview%3Dtrue)
```
📡 HTTP Error 404: http://labs.w3.org/spec-generator/uploads/iINKJg
```
_If you don't have …

Improve markup of enumeration tables

---

webrtc-stats.html

One of the steps needed for #621.
> AFTER THIS PR HAS BEEN APPROVED BUT BEFORE LANDING IT:
> Create a corresponding webrtc-provisional-stats PR adding these metrics to that document instead.
The metrics removed in this PR are those not implemented according to:
- [wpt.fyi](https://wpt.fyi/results/webrtc-stats/supported-stats.html?label=experimental&label=master&aligned)
- https://webrtc-stats.callstats.io/verify/.
- [Dom's comment](https://github.com/w3c/webrtc-stats/issues/595#issuecomment-777557331)
Metrics are removed regardless if they are easy or hard to implement and regardless of their usefulness - this is entirely based on implementers' interest.
Everything is not covered in this PR, other stuff:
- #628
- #627
- #625
- #624
- #626
Stuff implemented but failing in the WPT:
- rid: …

Remove most unimplemented stats

---

webrtc-stats.html

One of the steps needed for #621.
> AFTER THIS PR HAS BEEN APPROVED BUT BEFORE LANDING IT:
> Create a corresponding webrtc-provisional-stats PR adding these metrics to that document instead.
This one is implemented by RTCInboundRtpStreamStats but not by RTCRemoteInboundRtpStreamStats. In order to remove it from remote-inbound-rtp without removing it from inbound-rtp, the definition is moved from RTCReceivedRtpStreamStats to RTCInboundRtpStreamStats.
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/626.html" title="Last updated on Jun 9, 2022, 1:21 PM UTC (d1bb8e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/626/68f614d...henbos:d1bb8e9.html" title="Last updated on Jun 9, 2022, 1:21 PM UTC (d1bb8e9)">Diff</a>

Remove remote-inbound-rtp.packetsDiscarded.

---

webrtc-stats.html

One of the steps needed for #621.
> AFTER THIS PR HAS BEEN APPROVED BUT BEFORE LANDING IT:
> Create a corresponding webrtc-provisional-stats PR adding these metrics to that document instead.
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/627.html" title="Last updated on Jun 9, 2022, 1:40 PM UTC (29695b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/627/af5fb42...henbos:29695b2.html" title="Last updated on Jun 9, 2022, 1:40 PM UTC (29695b2)">Diff</a>

Remove sctp-transport

---

webrtc-stats.html

One of the steps needed for #621.
> AFTER THIS PR HAS BEEN APPROVED BUT BEFORE LANDING IT:
> Create a corresponding webrtc-provisional-stats PR adding these metrics to that document instead.
As far as I understand, all implementations do RTCP multiplexing and there is never any need to have multiple transport stats objects.
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/625.html" title="Last updated on Jun 9, 2022, 2:19 PM UTC (8a3c2cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/625/643d3f0...henbos:8a3c2cb.html" title="Last updated on Jun 9, 2022, 2:19 PM UTC (8a3c2cb)">Diff</a>

Remove transport.rtcpTransportStatsId

---

webrtc-stats.html

Fixes #632.
This metric already exists in the provisional spec:
https://w3c.github.io/webrtc-provisional-stats/#dom-rtcinboundrtpstreamstats-jitterbuffertargetdelay
It was implemented in March, 2020 and was proven useful but it was not then exposed to JavaScript. Let's fix that
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/633.html" title="Last updated on Jun 2, 2022, 9:25 AM UTC (e7e9f1a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/633/c78394f...henbos:e7e9f1a.html" title="Last updated on Jun 2, 2022, 9:25 AM UTC (e7e9f1a)">Diff</a>

Add RTCInboundRtpStreamStats.jitterBufferTargetDelay

---

webrtc-stats.html

***
<a href="https://pr-preview.s3.amazonaws.com/ivocreusen/webrtc-stats/pull/641.html" title="Last updated on Jun 29, 2022, 2:56 PM UTC (45eb60c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/641/70b92b8...ivocreusen:45eb60c.html" title="Last updated on Jun 29, 2022, 2:56 PM UTC (45eb60c)">Diff</a>

Add jitterBufferMinimumDelay metric

---

webrtc-stats.html

exposing
https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-active
in stats as well.
Fixes #597
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/649.html" title="Last updated on Jul 22, 2022, 3:24 PM UTC (1eb96f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/649/dc3120a...fippo:1eb96f8.html" title="Last updated on Jul 22, 2022, 3:24 PM UTC (1eb96f8)">Diff</a>

outbound-rtp: add active flag

---

webrtc-stats.html

Fixes #662
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/669.html" title="Last updated on Sep 7, 2022, 12:56 PM UTC (0d6a871)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/669/b708dd3...henbos:0d6a871.html" title="Last updated on Sep 7, 2022, 12:56 PM UTC (0d6a871)">Diff</a>

Only expose RTCCodecStats objects currently in use

---

webrtc-stats.html

Fixes #676
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/682.html" title="Last updated on Sep 20, 2022, 2:54 PM UTC (85d77f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/682/072f9dd...henbos:85d77f1.html" title="Last updated on Sep 20, 2022, 2:54 PM UTC (85d77f1)">Diff</a>

Add RTCAudioPlayoutStats, synthesizedSamplesDuration and totalSamplesDuration

---

webrtc-stats.html

Fixes #680.
NOTE This PR is made on top of #682. This PR only related to totalPlayoutDelay and totalSamplesCount.
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/683.html" title="Last updated on Sep 20, 2022, 2:57 PM UTC (e211759)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/683/cfb8128...henbos:e211759.html" title="Last updated on Sep 20, 2022, 2:57 PM UTC (e211759)">Diff</a>

Add totalPlayoutDelay and totalSamplesCount to RTCAudioPlayoutStats.

---

webrtc-stats.html

Fixes #681
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/685.html" title="Last updated on Sep 20, 2022, 3:11 PM UTC (145be7a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/685/a2b7577...henbos:145be7a.html" title="Last updated on Sep 20, 2022, 3:11 PM UTC (145be7a)">Diff</a>

Add totalCaptureDelay and totalSamplesCaptured to RTCAudioSourceStats.

---

webrtc-stats.html

Fixes #677, #679.
Because sample drops and sample synthesization tend to happen in bursts it is useful to not only know the duration but also the number of "events" happened.
The definition for these are very similar to [concealmentEvents](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-concealmentevents).
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/688.html" title="Last updated on Sep 21, 2022, 9:20 AM UTC (391b21d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/688/8ae8a4c...henbos:391b21d.html" title="Last updated on Sep 21, 2022, 9:20 AM UTC (391b21d)">Diff</a>

Add droppedSamplesEvents and synthesizedSamplesEvents

---

webrtc-stats.html

Fixes #666, #675
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/670.html" title="Last updated on Sep 27, 2022, 11:05 AM UTC (e983a31)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/670/48530b8...henbos:e983a31.html" title="Last updated on Sep 27, 2022, 11:05 AM UTC (e983a31)">Diff</a>

Add powerEfficient[En/De]coder (#666) and fingerprint mitigations (#675).

---

webrtc-stats.html

diff best viewed ignoring whitespace
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/700.html" title="Last updated on Sep 27, 2022, 2:19 PM UTC (dc97b29)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/700/104c3ba...fippo:dc97b29.html" title="Last updated on Sep 27, 2022, 2:19 PM UTC (dc97b29)">Diff</a>

editorial: remove trailing whitespace

---

webrtc-stats.html

following
https://github.com/w3c/webrtc-pc/pull/2763
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/657.html" title="Last updated on Sep 22, 2022, 3:56 PM UTC (7cb54bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/657/b708dd3...fippo:7cb54bb.html" title="Last updated on Sep 22, 2022, 3:56 PM UTC (7cb54bb)">Diff</a>

relayProtocol: use RTCIceServerTransportProtocol struct

---

webrtc-stats.html

* foundation
* relatedAddress
* relatedPort
* usernameFragment
* tcpType
all of which are already defined for the ICE candidate object itself
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/611.html" title="Last updated on Nov 8, 2021, 8:46 AM UTC (9a90be0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/611/cb32f08...fippo:9a90be0.html" title="Last updated on Nov 8, 2021, 8:46 AM UTC (9a90be0)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/611.html" title="Last updated on Oct 4, 2022, 12:20 PM UTC (65f6bc6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/611/ad722e9...fippo:65f6bc6.html" title="Last updated on Oct 4, 2022, 12:20 PM UTC (65f6bc6)">Diff</a>

add missing fields to candidate stats

---

webrtc-stats.html

Fixes #695
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/701.html" title="Last updated on Oct 3, 2022, 3:07 PM UTC (864509d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/701/cd1ff2f...henbos:864509d.html" title="Last updated on Oct 3, 2022, 3:07 PM UTC (864509d)">Diff</a>

Move pause and freeze metrics from webrtc-provisional-stats.

---

webrtc-stats.html

fixes #638
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 4, 2022, 1:44 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Ffippo%2Fwebrtc-stats%2Fdc500ac21a3fc1bbdedbad33edb8dcdad291d439%2Fwebrtc-stats.html%3FisPreview%3Dtrue)
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
_If you don't have enough information above to solve the error …

make encoderImplementation/decoderImplementation video-only

---

webrtc-stats.html

which allows measuring the average time to receive an inbound video frame.
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/694.html" title="Last updated on Oct 4, 2022, 7:55 PM UTC (b9fbefd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/694/55d60dd...fippo:b9fbefd.html" title="Last updated on Oct 4, 2022, 7:55 PM UTC (b9fbefd)">Diff</a>

inbound-rtp: add frame assembly time

---

webrtc-stats.html

Fixes #673.
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/709.html" title="Last updated on Nov 29, 2022, 10:32 AM UTC (33f66cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/709/4da9296...henbos:33f66cb.html" title="Last updated on Nov 29, 2022, 10:32 AM UTC (33f66cb)">Diff</a>

Add RTCOutboundRtpStreamStats.scalabilityMode

---

webrtc-stats.html

Fixes #712
A fullscreen element is not as trustworthy enough as a website whose able to fullscreen may just have a <video> element and does not require that WebRTC is used for purpose. This makes gUM access as the sole requirement for exposing hardware capabilities. This is a PR implementing the suggestions of #712.
***
<a href="https://pr-preview.s3.amazonaws.com/eshrubs/webrtc-stats/pull/713.html" title="Last updated on Dec 1, 2022, 4:38 PM UTC (468be14)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/713/52dc140...eshrubs:468be14.html" title="Last updated on Dec 1, 2022, 4:38 PM UTC (468be14)">Diff</a>

Remove fullscreen contexts hardware capability exposure

---

webrtc-stats.html

Fixes #719
***
<a href="https://pr-preview.s3.amazonaws.com/Hernqvist/webrtc-stats/pull/720.html" title="Last updated on Dec 14, 2022, 10:26 AM UTC (4b1ba78)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/720/d0dc3aa...Hernqvist:4b1ba78.html" title="Last updated on Dec 14, 2022, 10:26 AM UTC (4b1ba78)">Diff</a>

Change RTCAudioPlayoutStats::totalSamplesCount to unsigned long long

---

webrtc-stats.html

Fixes #716.
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/717.html" title="Last updated on Dec 13, 2022, 10:51 AM UTC (be9918b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/717/d0dc3aa...henbos:be9918b.html" title="Last updated on Dec 13, 2022, 10:51 AM UTC (be9918b)">Diff</a>

Add framesRendered, update totalInterFrameDelay.

---

webrtc-stats.html

The `RTCStats` dictionary is normatively defined in WebRTC and reproduced in WebRTC Stats for ease of reference only. The IDL block is correctly flagged as informative, but ReSpec still exports the IDL term, meaning that `{{RTCStats}}` can either be interpreted to mean:
1. a normative reference to the `RTCStats` dictionary defined in WebRTC
2. an informative reference to the `RTCStats` dictionary reproductionin WebRTC Stats.
The informative reproduction should not be exported. This update tells ReSpec not to export `RTCStats`. Note that there is no way (at least none that I'm aware of) to do that directly within the IDL block, so this moves the definition to the prose that precedes the IDL block.
Via https://github.com/w3c/webref/issues/306#issuecomment-1355169213
***
<a …

Don't export the informative RTCStats reproduction

---

webrtc-stats.html

Fixes a minor issue with example code: [RTCStatsReport is a map,](https://www.w3.org/TR/webrtc/#dom-rtcstatsreport) so property accessors shouldn't be expected. The `.get()` method should be used instead.
***
<a href="https://pr-preview.s3.amazonaws.com/redoPop/webrtc-stats/pull/726.html" title="Last updated on Jan 12, 2023, 6:10 PM UTC (94f2339)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/726/d65d1b0...redoPop:94f2339.html" title="Last updated on Jan 12, 2023, 6:10 PM UTC (94f2339)">Diff</a>

Fix stats object reference in example code

---

webrtc-stats.html

which showed up as
RTCInboundRtpStreamStats/decoderImplementation}}
due to extra closing }}
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/734.html" title="Last updated on Feb 16, 2023, 5:37 PM UTC (61efd4a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/734/2ada0c9...fippo:61efd4a.html" title="Last updated on Feb 16, 2023, 5:37 PM UTC (61efd4a)">Diff</a>

editorial: fix decoderImplementation idl reference

---

webrtc-stats.html

which was causing a weird indent:
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/738.html" title="Last updated on Mar 3, 2023, 8:48 AM UTC (44197d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/738/95726c2...fippo:44197d2.html" title="Last updated on Mar 3, 2023, 8:48 AM UTC (44197d2)">Diff</a>

Fix wrong html tag for mediaSourceId description

---

webrtc-stats.html

fixes #656
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/733.html" title="Last updated on Mar 7, 2023, 2:28 PM UTC (1db3085)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/733/2ada0c9...fippo:1db3085.html" title="Last updated on Mar 7, 2023, 2:28 PM UTC (1db3085)">Diff</a>

mark totalInterFrameDelay and totalSquaredInterFrameDelay as video-only

---

webrtc-stats.html

for consistency with the description and other places where packets are counted.
Note that in RTCP receiver reports this is still a 32 bit field.
(this is widening the field width so *should* be safe)
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/744.html" title="Last updated on Mar 7, 2023, 4:50 PM UTC (a841960)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/744/063ffa4...fippo:a841960.html" title="Last updated on Mar 7, 2023, 4:50 PM UTC (a841960)">Diff</a>

Make RTCRtpSentRtpStreamStats.packetsSent unsigned long long

---

webrtc-stats.html

and reference IANA media type registry
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/748.html" title="Last updated on Mar 16, 2023, 10:30 AM UTC (a583420)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/748/3057aa7...fippo:a583420.html" title="Last updated on Mar 16, 2023, 10:30 AM UTC (a583420)">Diff</a>

fix codec mimeType casing

---

webrtc-stats.html

fixes #736 with some editorial drive-bys.
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/745.html" title="Last updated on Mar 21, 2023, 6:40 PM UTC (b697781)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/745/063ffa4...fippo:b697781.html" title="Last updated on Mar 21, 2023, 6:40 PM UTC (b697781)">Diff</a>

Clarify that metrics are omitted when their value is not yet determined

---

webrtc-stats.html

fixs #753
***
<a href="https://pr-preview.s3.amazonaws.com/bdrtc/webrtc-stats/pull/754.html" title="Last updated on Apr 21, 2023, 7:37 AM UTC (3440385)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/754/1e31e7c...bdrtc:3440385.html" title="Last updated on Apr 21, 2023, 7:37 AM UTC (3440385)">Diff</a>

Change playout delay to jitter buffer target

---

webrtc-stats.html

* retransmittedBytesReceived
* retransmittedPacketsReceived
similar to the outbound-rtp ones. However, they are only defined
when RTX is negotiated as it is impossible to determine whether
a received packet is a retransmission otherwise.
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/735.html" title="Last updated on Mar 7, 2023, 4:00 PM UTC (97daa37)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/735/95726c2...fippo:97daa37.html" title="Last updated on Mar 7, 2023, 4:00 PM UTC (97daa37)">Diff</a>

specifiy inbound-rtp RTX statistics

---

webrtc-stats.html

fixes #755
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/756.html" title="Last updated on May 3, 2023, 6:30 AM UTC (e8ad4b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/756/2b6f736...fippo:e8ad4b9.html" title="Last updated on May 3, 2023, 6:30 AM UTC (e8ad4b9)">Diff</a>

Clarify inbound-rtp RTX handling

---

webrtc-stats.html

fixes #740
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/743.html" title="Last updated on May 11, 2023, 2:26 PM UTC (50e3b9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/743/063ffa4...fippo:50e3b9a.html" title="Last updated on May 11, 2023, 2:26 PM UTC (50e3b9a)">Diff</a>

Clarify when the candidate pair bandwidth estimation(s) exists

---

webrtc-stats.html

similar to how retransmittedBytesReceived is defined.
Fixes #751
For audio "FEC" usually means opus inband FEC (also known as low-bitrate redundacy, LBRR). This is typically sent together with an actual opus primary frame as secondary payload. Yet we count those as fecPacketsReceived but you can't add or subtract this from the RTP packets received. Since this is part of the same RTP payload counting separate fecHeaderBytesReceived does not make sense (we do not count RTP headers separately for RTX either btw)
For video we have two FEC mechanisms, ULPFEC and FLEXFEC.
* FlexFEC uses a separate SSRC so is similar to RTX when it comes to counting things. I do not think that implementations currently properly account for flexfec bytes but the rationale that it should be a subset of …

Specify fecBytesReceived

---

webrtc-stats.html

since it is an abbreviation defined in RFC 3550 and used in uppercase there.
Not replaced where it refers to the idl dictionary key.
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/764.html" title="Last updated on Jul 20, 2023, 1:54 PM UTC (d595fe9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/764/611d409...fippo:d595fe9.html" title="Last updated on Jul 20, 2023, 1:54 PM UTC (d595fe9)">Diff</a>

editorial: replace some lower-case `ssrc` with uppercase `SSRC`

---

webrtc-stats.html

which is already defined by inheritance
Fixes #690
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/766.html" title="Last updated on Jul 25, 2023, 9:59 AM UTC (266944d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/766/f6a0c81...fippo:266944d.html" title="Last updated on Jul 25, 2023, 9:59 AM UTC (266944d)">Diff</a>

Remove duplicate RTCInboundRtpStreamStats `kind`

---

webrtc-stats.html

For RTX this was previously defined in
https://w3c.github.io/webrtc-provisional-stats/#dom-rtcoutboundrtpstreamstats-rtxssrc
(only for outbound)
For FEC it is only defined for inbound-rtp due to the lack of a sender-side implementation of flexfec (this does not apply to ulpfec which uses the same SSRC)
fixes #751 (once again)
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/765.html" title="Last updated on Jul 24, 2023, 5:52 PM UTC (16e4480)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/765/611d409...fippo:16e4480.html" title="Last updated on Jul 24, 2023, 5:52 PM UTC (16e4480)">Diff</a>

add rtxSsrc to inbound-rtp and outbound-rtp stats and fecSsrc to inbound-rtp

---

webrtc-stats.html

Fixes #729
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/763.html" title="Last updated on Jun 22, 2023, 2:56 PM UTC (54ddf23)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/763/611d409...henbos:54ddf23.html" title="Last updated on Jun 22, 2023, 2:56 PM UTC (54ddf23)">Diff</a>

Delete 'retiring stats objects' section.

---

webrtc-stats.html

in addition to the IDL. Follow-up to #766
Fixes #690
(thanks @vr000m for catching it)
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/767.html" title="Last updated on Aug 4, 2023, 6:53 AM UTC (001b1b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/767/bb3930d...fippo:001b1b0.html" title="Last updated on Aug 4, 2023, 6:53 AM UTC (001b1b0)">Diff</a>

Remove duplicate definition of RTCInboundRtpStreamStats kind

---

webrtc-stats.html

Fixes #741 
The latency and dropped metrics are now part of [track.stats](https://w3c.github.io/mediacapture-extensions/#the-mediastreamtrackaudiostats-interface)
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/773.html" title="Last updated on Dec 7, 2023, 3:36 PM UTC (2bcb9f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/773/a82fba9...henbos:2bcb9f1.html" title="Last updated on Dec 7, 2023, 3:36 PM UTC (2bcb9f1)">Diff</a>

Remove audio capture stats that have moved to MediaStreamTrack's stats

---

webrtc-stats.html

Fixes #775.
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/777.html" title="Last updated on Jan 12, 2024, 10:18 AM UTC (4d5a62b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/777/12c9dd3...henbos:4d5a62b.html" title="Last updated on Jan 12, 2024, 10:18 AM UTC (4d5a62b)">Diff</a>

Replace 'Does not map/exist' with 'MUST NOT map/exist'

---

webrtc-stats.html

Fixes #776
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/webrtc-stats/pull/778.html" title="Last updated on Jan 12, 2024, 10:27 AM UTC (59b47d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/778/12c9dd3...henbos:59b47d4.html" title="Last updated on Jan 12, 2024, 10:27 AM UTC (59b47d4)">Diff</a>

Replace 'is not present' with 'MUST NOT be [= map/exist | present =]'

---

webrtc-stats.html
webrtc-stats.js

fixes #779
oddly this does not render as `as defined by [RFC8829] (section 5.8.)` like the corresponding part in [webrtc-pc](https://w3c.github.io/webrtc-pc/#rtcrtpcodec) -- and as this shows getting the section numbers wrong is easy ;-)
It seems we need [linkToJsep magic](https://github.com/w3c/webrtc-pc/blob/main/webrtc.js#L105)
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/780.html" title="Last updated on Jan 25, 2024, 3:24 PM UTC (df1c1ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/780/12c9dd3...fippo:df1c1ff.html" title="Last updated on Jan 25, 2024, 3:24 PM UTC (df1c1ff)">Diff</a>

clarify that sdpFmtpLine may not be there

---

webrtc-stats.html

after https://github.com/w3c/webrtc-pc/pull/2773 decided to deprecate the url in the event.
(editorial)
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/782.html" title="Last updated on Mar 7, 2024, 3:37 PM UTC (f936b3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/782/fdffc88...fippo:f936b3b.html" title="Last updated on Mar 7, 2024, 3:37 PM UTC (f936b3b)">Diff</a>

sync local-candidate url definition with webrtc-pc

---

webrtc-stats.html

as described in RFC 5245 15.1
If a candidate is server *or* peer reflexive,
<rel-addr> and <rel-port> are equal to the base for that
server or peer reflexive candidate
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/783.html" title="Last updated on Feb 24, 2024, 10:51 AM UTC (1f09e93)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/783/a82fba9...fippo:1f09e93.html" title="Last updated on Feb 24, 2024, 10:51 AM UTC (1f09e93)">Diff</a>

raddr+rport can be set for peer-reflexive candidates as well

---

webrtc-stats.html

Fixes #787
This PR adds new statistics for a corruption probability measure of a received video stream.
We include both the sum and sum of squares for this measure, so that a variance can be calculated.
***
<a href="https://pr-preview.s3.amazonaws.com/sprangerik/webrtc-stats/pull/788.html" title="Last updated on Oct 29, 2024, 1:35 PM UTC (55c3100)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/788/d6c2dbf...sprangerik:55c3100.html" title="Last updated on Oct 29, 2024, 1:35 PM UTC (55c3100)">Diff</a>

Add definitions of corruption detection measurements

---

webrtc-stats.html

(I would not agree with "simulcast layer is dropped for BW reasons, stats go away) but that is orthogonal to the typo
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/798.html" title="Last updated on Mar 1, 2025, 4:30 AM UTC (cc81fc7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/798/71dbce9...fippo:cc81fc7.html" title="Last updated on Mar 1, 2025, 4:30 AM UTC (cc81fc7)">Diff</a>

fix typo: simulast

---

l4s-explainer.md
webrtc-stats.html

These counters also depend on RFC8888 being deployed.
An explainer for the design is included.
Fixes #793
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/pull/792.html" title="Last updated on Mar 24, 2025, 7:31 PM UTC (e820135)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/792/02094bc...e820135.html" title="Last updated on Mar 24, 2025, 7:31 PM UTC (e820135)">Diff</a>

Add counters that support deployment of L4S

---

webrtc-stats.html

Fixes #797.
[Original description] The RTP sender is created at setLocalDescription time, i.e. has-local-offer or stable. This is consistent with the transceiver's MID value also being assigned at this point in time.
- I have verified that this description is consistent with Chrome Stable: [offerer fiddle](https://jsfiddle.net/gy8us4Lk/) and [answerer fiddle](https://jsfiddle.net/5ytoqzum/).
[Update based on review] The RTP sender is configured when we go back to stable signaling state (SDP answer is set), this means both Chrome and Firefox needs to update its behavior
WPT test coverage is being added [here](https://chromium-review.googlesource.com/c/chromium/src/+/6402253).
- Chrome currently passes the first test and fails the second but I'm happy to make Chrome pass both tests.
***
<a …

Update RTP lifetime description: outbound-rtp to be created before first packet is sent

---

webrtc-stats.html

Fixes #801.
Sorting requires it to be an index. Sorting or not, we need to know which encoding has which SSRC. and different streams may use different RIDs for different semantics, e.g. {q,h,f} = {quarter, half, full} may be used for camera streams and {l,h} = {lowFps, highFps} may be used for screenshare streams. Or something else, we don't want to have coupling between the stats pipeline and arbitrary app naming conventions somewhere else which are not set in stone or consistent.
The stats pipeline is typically a separate part of the code base or even an entirely external tool like https://fippo.github.io/webrtc-dump-importer/ which does not have access to JS APIs like getParameters().
The stats pipeline often executes after the call has ended, so index needs to be stored inside the …

Add outbound-rtp.encodingIndex.

---

webrtc-stats.html
webrtc-stats.js

This is similar to qpSum but codec-independent.
Since PSNR requires additional computation it is defined with an
accompanying psnrMeasurements counter to allow the computation of
an average PSNR.
Defined as a record with components for the Y, U and V planes respectively.
See also
https://datatracker.ietf.org/doc/html/rfc8761#section-5
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/794.html" title="Last updated on Jul 10, 2025, 2:41 PM UTC (18f34e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/794/02094bc...fippo:18f34e5.html" title="Last updated on Jul 10, 2025, 2:41 PM UTC (18f34e5)">Diff</a>

Add PSNR (Y/U/V) for outbound-rtp

---

webrtc-stats.html

Lets make tabs-vs-spaces our next argument!
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/webrtc-stats/pull/812.html" title="Last updated on Aug 28, 2025, 2:16 PM UTC (40e420c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-stats/812/efecbcd...fippo:40e420c.html" title="Last updated on Aug 28, 2025, 2:16 PM UTC (40e420c)">Diff</a>

remove extra span and fix indent
